language: node_js

node_js:
  - stable

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node app.js &
  - node_modules/.bin/newman run tests_postman/carlift.postman_collection.json

notifications:
  email: 
    - augustedstrom@hotmail.com
