sudo: false

language: node_js

node_js:
  - stable

branches:
  - master

cache:
  npm: false

install:
  - npm install

script:
  - node app.js
  - npm test

notifications:
  slack: softwareengin-bbu9772:767bZsCxdYEGErlRZC1PKPny

  email: false
