sudo: false

language: node_js

node_js:
  - stable

branches:
  - master

cache:
  directories:
    -node_modules

install:
  - npm install

script:
  - npm run build
  - npm run test

notifications:
  slack: softwareengin-bbu9772:767bZsCxdYEGErlRZC1PKPny

  email: false
